---
# Config tasks for ansible-role-docksal.

- name: "Docksal | get current value of {{ variable.key }}."
  command: "fin config get --global --env {{ variable.key }}"
  args:
    chdir: "/home/{{ docksal__user }}"
  become: true
  become_user: "{{ docksal__user }}"
  register: "dl__config_get"
  changed_when: false
  no_log: "{{ variable.secret is defined }}"

- name: "Docksal | set {{ variable.key }} to {{ (variable.secret is defined)|ternary('XXXXXX', variable.value) }}."
  command: "fin config set --global {{ variable.key }}={{ variable.value|quote }}"
  args:
    chdir: "/home/{{ docksal__user }}"
  become: true
  become_user: "{{ docksal__user }}"
  when: "variable.value != dl__config_get.stdout|regex_replace('[\\\"]', '')"
