---
# Docksal global config tasks for ansible-role-docksal

- name: Manage Docksal global config values.
  block:
    - name: Get current value of {{ variable.key }}.
      command: "fin config get --global --env {{ variable.key }}"
      register: rd_docksal_config_get
      changed_when: false
      no_log: "{{ variable.secret is defined }}"

    - name: Set {{ variable.key }} to {{ (variable.secret is defined)|ternary('XXXXXXX', variable.value) }}.
      command: "fin config set --global {{ variable.key }}={{ variable.value }}"
      no_log: "{{ variable.secret is defined }}"
      when:
        - "variable.value not in rd_docksal_config_get.stdout"

  become: true
  become_user: "{{ docksal_user }}"
