---
# tasks file for ansible-role-docksal

- name: Install Docksal.
  include_tasks: "docksal-install.yml"

- name: Include global Docksal config tasks.
  include_tasks:
    file: "docksal-global-config.yml"
    apply:
      tags:
        - docksal
  loop: "{{ docksal_global_config }}"
  loop_control:
    loop_var: variable

- name: Reset the Docksal system.
  command: "{{ docksal_fin_path }} system reset"
  changed_when: false

- name: Update Docksal.
  command: "fin update"
  # There seems to be no reliable way to figure out if anything has changed
  # when this command runs--it ALWAYS reports 'Pulling from...' or 'downloaded'
  # etc. So we sacrifice a bit of strict idempotency for the option to reliably
  # use --check when running playbooks containing this role.
  changed_when: false
