---
# update tasks for ansible-role-docksal

- name: "Docksal | Update fin binary to {{ fact__latest }} (was: {{ (fact__current == '0')|ternary('not installed', fact__current) }})."
  ansible.builtin.command: "fin update"
  become: true
  become_user: "{{ docksal_user }}"
