---
dependency:
  name: galaxy
  options:
    # Bizarrely, Molecule treats this path completely differently from all
    # other paths that can be specified in this file.
    role-file: molecule/requirements.yml
# lint: |
#   ./scripts/lint.sh
driver:
  name: docker
platforms:
  - name: instance
    # geerlingguy/docker-ubuntu2204-ansible
    image: geerlingguy/docker-${MOLECULE_UBUNTU_VERSION:-"ubuntu2004"}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../group_vars
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
  directory: ../../tests
