---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: Create /etc/docker directory.
      file:
        path: "{{ docker_daemon_directory_path }}"
        state: directory
        owner: root
        group: root

    - name: Create /etc/docker/daemon.json
      copy:
        content: |
          {
            "storage-driver": "vfs"
          }
        dest: "{{ docker_daemon_directory_path }}/daemon.json"
        owner: root
        group: root
  roles:
    - "weareinteractive.apt"
    - "weareinteractive.users"
    - "geerlingguy.security"
