---
# This is an example playbook to execute Ansible tests.

- name: "Verify Docksal install and configuration."
  hosts: all
  tasks:
    - name: "Test | Ensure fin binary exists."
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tests/test-fin.yml"

    - name: "Test | Ensure that docker is installed and operational."
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tests/test-docker.yml"

    - name: "Test | verify fin global config settings."
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tests/test-config.yml"

    - name: "Test | Create and serve a project with Docksal."
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tests/test-project.yml"
